# Generated by Django 5.2.3 on 2025-09-15 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文档名称")),
                ("size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "file_object_id",
                    models.CharField(max_length=255, verbose_name="AI服务文件ID"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="文件哈希"
                    ),
                ),
                ("last_modified", models.BigIntegerField(verbose_name="文件最后修改时间")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "db_table": "ai_reading_document",
                "unique_together": {("user", "name", "size", "last_modified")},
            },
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("upload", "上传"),
                            ("analyze", "分析"),
                            ("question", "提问"),
                            ("view", "查看"),
                        ],
                        max_length=20,
                        verbose_name="访问类型",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.document",
                        verbose_name="文档",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档访问记录",
                "verbose_name_plural": "文档访问记录",
                "db_table": "ai_reading_access",
                "ordering": ["-access_time"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(verbose_name="总结")),
                ("key_points", models.JSONField(default=list, verbose_name="核心要点")),
                ("keywords", models.JSONField(default=list, verbose_name="关键词")),
                ("entities", models.JSONField(default=list, verbose_name="实体识别结果")),
                (
                    "suggested_questions",
                    models.JSONField(default=list, verbose_name="推荐问题"),
                ),
                (
                    "analysis_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.document",
                        verbose_name="文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档分析",
                "verbose_name_plural": "文档分析",
                "db_table": "ai_reading_analysis",
            },
        ),
        migrations.CreateModel(
            name="QAHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题")),
                ("answer", models.TextField(verbose_name="回答")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提问时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.document",
                        verbose_name="文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "问答历史",
                "verbose_name_plural": "问答历史",
                "db_table": "ai_reading_qa_history",
                "ordering": ["-created_time"],
            },
        ),
    ]
