# Generated by Django 5.2.3 on 2025-09-17 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_document_documentaccess_documentanalysis_qahistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="正向提示词")),
                (
                    "negative_prompt",
                    models.TextField(blank=True, null=True, verbose_name="反向提示词"),
                ),
                (
                    "enhanced_prompt",
                    models.TextField(blank=True, null=True, verbose_name="增强后的提示词"),
                ),
                ("size", models.CharField(max_length=20, verbose_name="图像尺寸")),
                ("n", models.IntegerField(default=1, verbose_name="生成数量")),
                (
                    "prompt_extend",
                    models.BooleanField(default=True, verbose_name="智能改写"),
                ),
                ("watermark", models.BooleanField(default=True, verbose_name="添加水印")),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="风格"
                    ),
                ),
                (
                    "shot_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="景别"
                    ),
                ),
                (
                    "angle",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="视角"
                    ),
                ),
                (
                    "shooting_technique",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="拍摄技法"
                    ),
                ),
                (
                    "lighting",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="光线效果"
                    ),
                ),
                (
                    "api_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="API请求ID"
                    ),
                ),
                ("api_usage", models.JSONField(default=dict, verbose_name="API使用统计")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图像生成任务",
                "verbose_name_plural": "图像生成任务",
                "db_table": "ai_image_generation_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(verbose_name="原始图像URL")),
                ("saved_path", models.CharField(max_length=500, verbose_name="保存路径")),
                ("saved_url", models.URLField(verbose_name="保存后的URL")),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "orig_prompt",
                    models.TextField(blank=True, null=True, verbose_name="原始提示词"),
                ),
                (
                    "actual_prompt",
                    models.TextField(blank=True, null=True, verbose_name="实际使用的提示词"),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="宽度"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="高度"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="格式"
                    ),
                ),
                ("download_time", models.DateTimeField(verbose_name="下载时间")),
                (
                    "download_duration",
                    models.FloatField(blank=True, null=True, verbose_name="下载耗时(秒)"),
                ),
                (
                    "is_downloaded",
                    models.BooleanField(default=False, verbose_name="是否已下载"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                ("download_count", models.IntegerField(default=0, verbose_name="下载次数")),
                (
                    "last_viewed",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后查看时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chat.imagegenerationtask",
                        verbose_name="生成任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成的图像",
                "verbose_name_plural": "生成的图像",
                "db_table": "ai_generated_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserImageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tasks", models.IntegerField(default=0, verbose_name="总任务数")),
                ("total_images", models.IntegerField(default=0, verbose_name="总图像数")),
                ("success_tasks", models.IntegerField(default=0, verbose_name="成功任务数")),
                ("failed_tasks", models.IntegerField(default=0, verbose_name="失败任务数")),
                (
                    "total_storage_used",
                    models.BigIntegerField(default=0, verbose_name="使用存储空间(字节)"),
                ),
                (
                    "total_api_calls",
                    models.IntegerField(default=0, verbose_name="API调用次数"),
                ),
                (
                    "favorite_style",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="偏好风格"
                    ),
                ),
                (
                    "favorite_size",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="偏好尺寸"
                    ),
                ),
                (
                    "avg_images_per_task",
                    models.FloatField(default=1.0, verbose_name="平均每任务图像数"),
                ),
                (
                    "first_generation",
                    models.DateTimeField(blank=True, null=True, verbose_name="首次生成时间"),
                ),
                (
                    "last_generation",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后生成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户图像统计",
                "verbose_name_plural": "用户图像统计",
                "db_table": "ai_user_image_stats",
            },
        ),
        migrations.AddIndex(
            model_name="imagegenerationtask",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_image_ge_user_id_e9b37d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagegenerationtask",
            index=models.Index(
                fields=["task_id"], name="ai_image_ge_task_id_8bfedf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagegenerationtask",
            index=models.Index(fields=["status"], name="ai_image_ge_status_36f09b_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(
                fields=["task", "-created_at"], name="ai_generate_task_id_d94bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(
                fields=["is_downloaded"], name="ai_generate_is_down_250630_idx"
            ),
        ),
    ]
