# Generated by Django 5.2.3 on 2025-09-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_imagegenerationtask_generatedimage_userimagestats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="original_url",
            field=models.URLField(max_length=1000, verbose_name="原始图像URL"),
        ),
        migrations.AlterField(
            model_name="generatedimage",
            name="saved_url",
            field=models.URLField(max_length=1000, verbose_name="保存后的URL"),
        ),
    ]
