# Generated by Django 5.2.3 on 2025-09-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_increase_url_field_length"),
        ("users", "0005_user_theme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("speech_to_text", "语音转文字"),
                            ("text_to_speech", "文字转语音"),
                            ("voice_clone", "语音克隆"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "input_text",
                    models.TextField(blank=True, null=True, verbose_name="输入文本"),
                ),
                (
                    "input_audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio-inputs/",
                        verbose_name="输入音频文件",
                    ),
                ),
                (
                    "input_audio_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="输入音频URL"
                    ),
                ),
                (
                    "output_text",
                    models.TextField(blank=True, null=True, verbose_name="输出文本"),
                ),
                (
                    "output_audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio-outputs/",
                        verbose_name="输出音频文件",
                    ),
                ),
                (
                    "output_audio_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="输出音频URL"
                    ),
                ),
                (
                    "api_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="API请求ID"
                    ),
                ),
                (
                    "api_usage",
                    models.JSONField(blank=True, default=dict, verbose_name="API使用统计"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "音频任务",
                "verbose_name_plural": "音频任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAudioStats",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "total_speech_to_text",
                    models.IntegerField(default=0, verbose_name="语音转文字次数"),
                ),
                (
                    "total_text_to_speech",
                    models.IntegerField(default=0, verbose_name="文字转语音次数"),
                ),
                (
                    "total_voice_clone",
                    models.IntegerField(default=0, verbose_name="语音克隆次数"),
                ),
                (
                    "total_audio_duration",
                    models.FloatField(default=0, verbose_name="总音频时长(秒)"),
                ),
                (
                    "total_storage_used",
                    models.BigIntegerField(default=0, verbose_name="总存储使用(字节)"),
                ),
                (
                    "last_audio_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后音频处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户音频统计",
                "verbose_name_plural": "用户音频统计",
            },
        ),
        migrations.CreateModel(
            name="UserVideoStats",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "total_text_to_video",
                    models.IntegerField(default=0, verbose_name="文生视频次数"),
                ),
                (
                    "total_image_to_video",
                    models.IntegerField(default=0, verbose_name="图生视频次数"),
                ),
                (
                    "total_videos_generated",
                    models.IntegerField(default=0, verbose_name="总生成视频数"),
                ),
                (
                    "total_video_duration",
                    models.FloatField(default=0, verbose_name="总视频时长(秒)"),
                ),
                (
                    "total_storage_used",
                    models.BigIntegerField(default=0, verbose_name="总存储使用(字节)"),
                ),
                (
                    "total_generation_time",
                    models.FloatField(default=0, verbose_name="总生成耗时(秒)"),
                ),
                (
                    "average_generation_time",
                    models.FloatField(default=0, verbose_name="平均生成耗时(秒)"),
                ),
                (
                    "last_generation_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后生成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户视频统计",
                "verbose_name_plural": "用户视频统计",
            },
        ),
        migrations.CreateModel(
            name="VideoStylePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="风格名称"),
                ),
                ("description", models.TextField(verbose_name="风格描述")),
                ("style_keywords", models.TextField(verbose_name="风格关键词")),
                (
                    "recommended_model",
                    models.CharField(
                        default="wanx2.1-t2v-turbo", max_length=50, verbose_name="推荐模型"
                    ),
                ),
                (
                    "default_resolution",
                    models.CharField(
                        default="1280*720", max_length=20, verbose_name="默认分辨率"
                    ),
                ),
                (
                    "default_duration",
                    models.IntegerField(default=5, verbose_name="默认时长"),
                ),
                ("default_fps", models.IntegerField(default=25, verbose_name="默认帧率")),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="video-style-previews/",
                        verbose_name="预览图",
                    ),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "视频风格预设",
                "verbose_name_plural": "视频风格预设",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="SpeechToTextTask",
            fields=[
                (
                    "audio_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="chat.audiotask",
                        verbose_name="音频任务",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="zh-cn", max_length=10, verbose_name="语言"),
                ),
                (
                    "model",
                    models.CharField(
                        default="paraformer-realtime-v1",
                        max_length=50,
                        verbose_name="识别模型",
                    ),
                ),
                (
                    "format",
                    models.CharField(default="pcm", max_length=10, verbose_name="音频格式"),
                ),
                ("sample_rate", models.IntegerField(default=16000, verbose_name="采样率")),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="置信度"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="音频时长(秒)"),
                ),
            ],
            options={
                "verbose_name": "语音转文字任务",
                "verbose_name_plural": "语音转文字任务",
            },
        ),
        migrations.CreateModel(
            name="TextToSpeechTask",
            fields=[
                (
                    "audio_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="chat.audiotask",
                        verbose_name="音频任务",
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        default="zhifeng_emo", max_length=50, verbose_name="音色"
                    ),
                ),
                ("speed", models.FloatField(default=1.0, verbose_name="语速")),
                ("volume", models.IntegerField(default=50, verbose_name="音量")),
                ("pitch", models.FloatField(default=1.0, verbose_name="音调")),
                (
                    "format",
                    models.CharField(default="mp3", max_length=10, verbose_name="输出格式"),
                ),
                ("sample_rate", models.IntegerField(default=22050, verbose_name="采样率")),
                (
                    "audio_duration",
                    models.FloatField(blank=True, null=True, verbose_name="音频时长(秒)"),
                ),
                (
                    "file_size",
                    models.IntegerField(blank=True, null=True, verbose_name="文件大小(字节)"),
                ),
            ],
            options={
                "verbose_name": "文字转语音任务",
                "verbose_name_plural": "文字转语音任务",
            },
        ),
        migrations.CreateModel(
            name="VoiceCloneTask",
            fields=[
                (
                    "audio_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="chat.audiotask",
                        verbose_name="音频任务",
                    ),
                ),
                (
                    "reference_audio",
                    models.FileField(
                        upload_to="voice-references/", verbose_name="参考音频"
                    ),
                ),
                ("reference_text", models.TextField(verbose_name="参考文本")),
                ("target_text", models.TextField(verbose_name="目标文本")),
                (
                    "model",
                    models.CharField(
                        default="sambert-v1", max_length=50, verbose_name="克隆模型"
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(blank=True, null=True, verbose_name="相似度评分"),
                ),
            ],
            options={
                "verbose_name": "语音克隆任务",
                "verbose_name_plural": "语音克隆任务",
            },
        ),
        migrations.CreateModel(
            name="VideoGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("text_to_video", "文生视频"), ("image_to_video", "图生视频")],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="文本提示词")),
                (
                    "input_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="video-inputs/",
                        verbose_name="输入图片",
                    ),
                ),
                (
                    "input_image_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="输入图片URL"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="wanx2.1-t2v-turbo", max_length=50, verbose_name="生成模型"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("720P", "1280x720"),
                            ("1080P", "1920x1080"),
                            ("1280*720", "1280x720"),
                            ("1920*1080", "1920x1080"),
                        ],
                        default="1280*720",
                        max_length=20,
                        verbose_name="分辨率",
                    ),
                ),
                ("duration", models.IntegerField(default=5, verbose_name="视频时长(秒)")),
                ("fps", models.IntegerField(default=25, verbose_name="帧率")),
                (
                    "output_video_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="输出视频URL"
                    ),
                ),
                (
                    "saved_video_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="保存的视频路径"
                    ),
                ),
                (
                    "video_file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="视频文件大小"
                    ),
                ),
                (
                    "enhanced_prompt",
                    models.TextField(blank=True, null=True, verbose_name="增强后的提示词"),
                ),
                (
                    "original_prompt",
                    models.TextField(blank=True, null=True, verbose_name="原始提示词"),
                ),
                (
                    "api_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="API请求ID"
                    ),
                ),
                (
                    "api_task_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="API任务ID"
                    ),
                ),
                (
                    "api_usage",
                    models.JSONField(blank=True, default=dict, verbose_name="API使用统计"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "submit_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="提交时间"),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="调度时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频生成任务",
                "verbose_name_plural": "视频生成任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_url",
                    models.URLField(max_length=1000, verbose_name="原始视频URL"),
                ),
                (
                    "saved_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="保存后的视频URL"
                    ),
                ),
                (
                    "saved_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="本地保存路径"
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="视频时长(秒)"),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="分辨率"
                    ),
                ),
                ("fps", models.IntegerField(blank=True, null=True, verbose_name="帧率")),
                (
                    "bitrate",
                    models.IntegerField(blank=True, null=True, verbose_name="比特率"),
                ),
                (
                    "is_downloaded",
                    models.BooleanField(default=False, verbose_name="是否已下载"),
                ),
                (
                    "download_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下载时间"),
                ),
                (
                    "download_error",
                    models.TextField(blank=True, null=True, verbose_name="下载错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_videos",
                        to="chat.videogenerationtask",
                        verbose_name="生成任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成的视频",
                "verbose_name_plural": "生成的视频",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="audiotask",
            index=models.Index(
                fields=["user", "task_type"], name="chat_audiot_user_id_584f1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiotask",
            index=models.Index(fields=["status"], name="chat_audiot_status_a22d65_idx"),
        ),
        migrations.AddIndex(
            model_name="audiotask",
            index=models.Index(
                fields=["created_at"], name="chat_audiot_created_bf54a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videogenerationtask",
            index=models.Index(
                fields=["user", "task_type"], name="chat_videog_user_id_b4a849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videogenerationtask",
            index=models.Index(fields=["status"], name="chat_videog_status_04bf2c_idx"),
        ),
        migrations.AddIndex(
            model_name="videogenerationtask",
            index=models.Index(
                fields=["created_at"], name="chat_videog_created_d2bad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videogenerationtask",
            index=models.Index(
                fields=["api_task_id"], name="chat_videog_api_tas_a7bbb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedvideo",
            index=models.Index(fields=["task"], name="chat_genera_task_id_27fa0d_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedvideo",
            index=models.Index(
                fields=["is_downloaded"], name="chat_genera_is_down_0d2381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedvideo",
            index=models.Index(
                fields=["created_at"], name="chat_genera_created_196074_idx"
            ),
        ),
    ]
