# Generated by Django 5.2.3 on 2025-10-13 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_audiotask_useraudiostats_uservideostats_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-is_pinned", "-pinned_at", "-updated_at"],
                "verbose_name": "对话",
                "verbose_name_plural": "对话",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置顶时间"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-is_pinned", "-pinned_at"],
                name="chat_conver_user_id_6196f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_conver_user_id_e2a76b_idx"
            ),
        ),
    ]
