# Generated by Django 5.2.3 on 2025-10-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_conversation_options_conversation_is_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="custom_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="自定义标题"
            ),
        ),
    ]
