# Generated by Django 5.2.3 on 2025-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_conversation_custom_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="image_source",
            field=models.CharField(
                choices=[("text_to_image", "文生图"), ("image_edit", "图像编辑")],
                db_index=True,
                default="text_to_image",
                max_length=20,
                verbose_name="图像来源",
            ),
        ),
    ]
