# Generated by Django 5.2.3 on 2025-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_generatedimage_image_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texttospeechtask",
            name="pitch",
        ),
        migrations.RemoveField(
            model_name="texttospeechtask",
            name="speed",
        ),
        migrations.RemoveField(
            model_name="texttospeechtask",
            name="volume",
        ),
        migrations.AddField(
            model_name="texttospeechtask",
            name="language_type",
            field=models.CharField(
                default="Chinese", max_length=50, verbose_name="语言类型"
            ),
        ),
        migrations.AlterField(
            model_name="texttospeechtask",
            name="voice",
            field=models.CharField(default="Cherry", max_length=50, verbose_name="音色"),
        ),
    ]
