# Generated by Django 5.2.3 on 2025-10-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_remove_texttospeechtask_pitch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogenerationtask",
            name="seed",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="随机种子"),
        ),
        migrations.AlterField(
            model_name="videogenerationtask",
            name="fps",
            field=models.IntegerField(default=24, verbose_name="帧率"),
        ),
        migrations.AlterField(
            model_name="videogenerationtask",
            name="model",
            field=models.CharField(
                default="wan2.5-t2v-preview", max_length=50, verbose_name="生成模型"
            ),
        ),
    ]
