# Generated by Django 5.2.3 on 2025-09-17 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="智能体名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("travel_assistant", "旅游助手"),
                            ("poetry_painting", "诗词绘画"),
                            ("customer_service", "客服助手"),
                        ],
                        max_length=50,
                        verbose_name="智能体类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="智能体描述")),
                (
                    "avatar",
                    models.URLField(blank=True, null=True, verbose_name="头像URL"),
                ),
                ("system_prompt", models.TextField(verbose_name="系统提示词")),
                (
                    "greeting_message",
                    models.CharField(
                        default="您好！我是您的智能助手，有什么可以帮助您的吗？",
                        max_length=500,
                        verbose_name="欢迎语",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "智能体",
                "verbose_name_plural": "智能体",
                "db_table": "agent_agent",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="对话标题")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后消息时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "message_count",
                    models.PositiveIntegerField(default=0, verbose_name="消息数量"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent.agent",
                        verbose_name="智能体",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "db_table": "agent_conversation",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user", "用户消息"),
                            ("assistant", "助手回复"),
                            ("system", "系统消息"),
                        ],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(default=0, verbose_name="消耗Token数"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent.conversation",
                        verbose_name="对话会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息记录",
                "verbose_name_plural": "消息记录",
                "db_table": "agent_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAgentStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_conversations",
                    models.PositiveIntegerField(default=0, verbose_name="总对话数"),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(default=0, verbose_name="总消息数"),
                ),
                (
                    "total_tokens_used",
                    models.PositiveIntegerField(default=0, verbose_name="总Token消耗"),
                ),
                (
                    "travel_conversations",
                    models.PositiveIntegerField(default=0, verbose_name="旅游助手对话数"),
                ),
                (
                    "poetry_conversations",
                    models.PositiveIntegerField(default=0, verbose_name="诗词绘画对话数"),
                ),
                (
                    "service_conversations",
                    models.PositiveIntegerField(default=0, verbose_name="客服助手对话数"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后使用时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户智能体统计",
                "verbose_name_plural": "用户智能体统计",
                "db_table": "agent_user_stats",
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "agent"], name="agent_conve_user_id_78ff40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["last_message_at"], name="agent_conve_last_me_3cf0a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="agent_messa_convers_a1e1dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["type"], name="agent_messa_type_988c45_idx"),
        ),
    ]
