# Generated by Django 5.2.3 on 2025-10-21 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PoetryPaintingConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="对话标题")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poetry_painting_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "诗词绘画对话",
                "verbose_name_plural": "诗词绘画对话",
                "db_table": "agent_poetry_painting_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PoetryPaintingWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poetry_theme", models.CharField(max_length=100, verbose_name="诗词主题")),
                (
                    "poetry_format",
                    models.CharField(
                        choices=[
                            ("five_jueju", "五言绝句"),
                            ("seven_jueju", "七言绝句"),
                            ("five_lvshi", "五言律诗"),
                            ("seven_lvshi", "七言律诗"),
                            ("ci", "词"),
                        ],
                        max_length=20,
                        verbose_name="诗词格式",
                    ),
                ),
                ("poetry_style", models.CharField(max_length=50, verbose_name="诗词风格")),
                ("poetry_content", models.TextField(verbose_name="诗词内容")),
                (
                    "poetry_title",
                    models.CharField(blank=True, max_length=100, verbose_name="诗词标题"),
                ),
                (
                    "poetry_analysis",
                    models.JSONField(blank=True, null=True, verbose_name="诗词分析"),
                ),
                ("painting_prompt", models.TextField(verbose_name="绘画提示词")),
                (
                    "painting_style",
                    models.CharField(
                        choices=[
                            ("chinese_ink", "水墨画"),
                            ("gongbi", "工笔画"),
                            ("oil_painting", "油画风格"),
                            ("watercolor", "水彩风格"),
                            ("modern", "现代艺术"),
                        ],
                        max_length=20,
                        verbose_name="绘画风格",
                    ),
                ),
                (
                    "painting_url",
                    models.URLField(max_length=1000, blank=True, null=True, verbose_name="画作URL"),
                ),
                (
                    "painting_local_path",
                    models.CharField(blank=True, max_length=500, verbose_name="本地路径"),
                ),
                (
                    "langgraph_state",
                    models.JSONField(blank=True, null=True, verbose_name="LangGraph状态"),
                ),
                (
                    "iteration_count",
                    models.IntegerField(default=1, verbose_name="迭代次数"),
                ),
                (
                    "user_rating",
                    models.IntegerField(blank=True, null=True, verbose_name="用户评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="agent.poetrypaintingconversation",
                        verbose_name="所属对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "诗词绘画作品",
                "verbose_name_plural": "诗词绘画作品",
                "db_table": "agent_poetry_painting_work",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PoetryPaintingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent.poetrypaintingconversation",
                        verbose_name="所属对话",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent.poetrypaintingwork",
                        verbose_name="关联作品",
                    ),
                ),
            ],
            options={
                "verbose_name": "诗词绘画消息",
                "verbose_name_plural": "诗词绘画消息",
                "db_table": "agent_poetry_painting_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="poetrypaintingwork",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="agent_poetr_convers_886fdf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="poetrypaintingwork",
            index=models.Index(
                fields=["poetry_theme"], name="agent_poetr_poetry__53d732_idx"
            ),
        ),
    ]
