# Generated by Django 5.2.3 on 2025-10-22 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0004_fix_painting_url_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerServiceKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("product", "产品咨询"),
                            ("order", "订单问题"),
                            ("technical", "技术支持"),
                            ("policy", "政策条款"),
                            ("faq", "常见问题"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("use_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_customer_service_knowledge",
                "ordering": ["-use_count", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="agent_custo_categor_819d9d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("resolved", "已解决"),
                            ("transferred", "已转人工"),
                            ("closed", "已关闭"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="客服咨询", max_length=255)),
                ("message_count", models.IntegerField(default=0)),
                ("satisfaction_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cs_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_customer_service_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "AI助手"),
                            ("system", "系统"),
                            ("human", "人工客服"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=50)),
                ("entities", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("tools_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent.customerservicesession",
                    ),
                ),
            ],
            options={
                "db_table": "agent_customer_service_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("resolved_sessions", models.IntegerField(default=0)),
                ("transferred_sessions", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("avg_session_messages", models.FloatField(default=0.0)),
                ("avg_satisfaction_score", models.FloatField(blank=True, null=True)),
                ("last_session_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cs_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_customer_service_stats",
            },
        ),
        migrations.AddIndex(
            model_name="customerservicesession",
            index=models.Index(
                fields=["user", "status"], name="agent_custo_user_id_335eee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerservicesession",
            index=models.Index(
                fields=["created_at"], name="agent_custo_created_c1bd44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerservicemessage",
            index=models.Index(
                fields=["session", "created_at"], name="agent_custo_session_edc71e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerservicemessage",
            index=models.Index(fields=["intent"], name="agent_custo_intent_64c97b_idx"),
        ),
    ]
