# Generated by Django 5.2.3 on 2025-10-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0005_customerserviceknowledgebase_customerservicesession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="知识库名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "创建中"),
                            ("processing", "处理中"),
                            ("ready", "就绪"),
                            ("error", "错误"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("document_count", models.IntegerField(default=0, verbose_name="文档数量")),
                ("chunk_count", models.IntegerField(default=0, verbose_name="切片数量")),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="总token数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cs_knowledge_base",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="助手名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "avatar",
                    models.CharField(
                        default="🤖", max_length=10, verbose_name="头像emoji"
                    ),
                ),
                (
                    "greeting_message",
                    models.TextField(
                        default="您好！我是智能客服助手，有什么可以帮您的吗？", verbose_name="开场白"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="自定义AI行为和语气", verbose_name="系统提示词"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("qwen-turbo", "Qwen Turbo - 快速"),
                            ("qwen-plus", "Qwen Plus - 平衡"),
                            ("qwen-max", "Qwen Max - 高质量"),
                        ],
                        default="qwen-plus",
                        max_length=50,
                        verbose_name="AI模型",
                    ),
                ),
                ("temperature", models.FloatField(default=0.7, verbose_name="创造性参数")),
                ("top_k", models.IntegerField(default=3, verbose_name="检索数量")),
                (
                    "enable_knowledge_base",
                    models.BooleanField(default=True, verbose_name="启用知识库"),
                ),
                (
                    "enable_order_query",
                    models.BooleanField(default=True, verbose_name="启用订单查询"),
                ),
                (
                    "enable_human_handoff",
                    models.BooleanField(default=True, verbose_name="启用人工转接"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认")),
                (
                    "total_conversations",
                    models.IntegerField(default=0, verbose_name="总对话数"),
                ),
                ("total_messages", models.IntegerField(default=0, verbose_name="总消息数")),
                (
                    "avg_satisfaction",
                    models.FloatField(blank=True, null=True, verbose_name="平均满意度"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cs_assistants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_bases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assistants",
                        to="agent.knowledgebase",
                        verbose_name="关联知识库",
                    ),
                ),
            ],
            options={
                "db_table": "cs_assistant",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.BigIntegerField(verbose_name="文件大小（字节）")),
                ("file_path", models.CharField(max_length=1000, verbose_name="文件路径")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[
                            ("auto", "智能切片"),
                            ("fixed", "固定长度"),
                            ("semantic", "语义切片"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("chunk_size", models.IntegerField(default=500, verbose_name="切片大小")),
                ("chunk_overlap", models.IntegerField(default=50, verbose_name="切片重叠")),
                (
                    "clean_strategy",
                    models.CharField(
                        choices=[("auto", "智能清洗"), ("basic", "基础清洗"), ("none", "不清洗")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("chunk_count", models.IntegerField(default=0, verbose_name="切片数量")),
                ("token_count", models.IntegerField(default=0, verbose_name="token数量")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="agent.knowledgebase",
                    ),
                ),
            ],
            options={
                "db_table": "cs_knowledge_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="切片内容")),
                ("chunk_index", models.IntegerField(verbose_name="切片索引")),
                (
                    "embedding",
                    models.TextField(blank=True, null=True, verbose_name="向量嵌入(JSON)"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("token_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="agent.knowledgebase",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="agent.knowledgedocument",
                    ),
                ),
            ],
            options={
                "db_table": "cs_document_chunk",
            },
        ),
        migrations.CreateModel(
            name="ChunkProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=50, verbose_name="处理步骤")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "开始"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent.knowledgedocument",
                    ),
                ),
            ],
            options={
                "db_table": "cs_chunk_processing_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["user", "status"], name="cs_knowledg_user_id_0d710e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerserviceassistant",
            index=models.Index(
                fields=["user", "is_active"], name="cs_assistan_user_id_f410ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="cs_document_documen_737674_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["knowledge_base"], name="cs_document_knowled_61e47f_idx"
            ),
        ),
    ]
