# Generated by Django 5.2.3 on 2025-10-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_knowledgebase_customerserviceassistant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="format",
            field=models.CharField(
                choices=[("text", "文本格式"), ("structured", "结构化格式"), ("image", "图片格式")],
                default="text",
                max_length=20,
                verbose_name="知识库格式",
            ),
        ),
    ]
