# Generated by Django 5.2.3 on 2025-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0007_knowledgebase_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="domain",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="文档领域"
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="intent_prompt",
            field=models.TextField(blank=True, null=True, verbose_name="意图识别提示词"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="key_points",
            field=models.JSONField(blank=True, default=list, verbose_name="核心要点"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="keywords",
            field=models.JSONField(blank=True, default=list, verbose_name="关键词"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="suggested_questions",
            field=models.JSONField(blank=True, default=list, verbose_name="推荐问题"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="文档总结"),
        ),
    ]
