# Generated by Django 5.2.3 on 2025-06-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="详细地址"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="城市"),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, default="中国", max_length=50, verbose_name="国家"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.CharField(blank=True, max_length=50, verbose_name="区县"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "男"),
                    ("female", "女"),
                    ("other", "其他"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="上次登录IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(blank=True, max_length=50, verbose_name="省份"),
        ),
        migrations.AddField(
            model_name="user",
            name="qq",
            field=models.CharField(blank=True, max_length=20, verbose_name="QQ"),
        ),
    ]
