# Generated by Django 5.2.3 on 2025-08-10 05:09

import django.db.models.deletion
from django.db import migrations, models


def create_initial_roles_and_migrate_users(apps, schema_editor):
    """创建初始角色并迁移用户数据"""
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')
    
    # 创建系统角色
    admin_role, _ = Role.objects.get_or_create(
        code='admin',
        defaults={
            'name': '管理员',
            'description': '系统管理员，拥有所有权限',
            'is_system': True
        }
    )
    
    staff_role, _ = Role.objects.get_or_create(
        code='staff',
        defaults={
            'name': '工作人员',
            'description': '系统工作人员，拥有部分管理权限',
            'is_system': True
        }
    )
    
    user_role, _ = Role.objects.get_or_create(
        code='user',
        defaults={
            'name': '普通用户',
            'description': '普通用户，拥有基本使用权限',
            'is_system': True
        }
    )
    
    # 根据 role_str 字段迁移用户角色
    for user in User.objects.all():
        if user.role_str == 'admin':
            user.user_role = admin_role
        elif user.role_str == 'staff':
            user.user_role = staff_role
        else:
            user.user_role = user_role
        user.save(update_fields=['user_role'])


def reverse_migration(apps, schema_editor):
    """反向迁移"""
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')
    
    # 清除用户角色关联
    User.objects.update(user_role=None)
    # 删除所有角色
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_address_user_birthday_user_city_user_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="role_str",
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="角色代码"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="角色名称")),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="是否系统角色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="角色权限"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["code"],
            },
        ),
        
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.role",
                verbose_name="用户角色对象",
            ),
        ),
        # 创建初始角色并迁移用户数据
        migrations.RunPython(create_initial_roles_and_migrate_users, reverse_migration),
    ]
