# Generated by Django 5.2.3 on 2025-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_create_role_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(blank=True, max_length=20, verbose_name="主题"),
        ),
    ]
